---
- hosts: aws
  tasks:

  - name: Install nginx
    yum:
      name: nginx
      state: latest
    become: true

  - name: Install httpd-tools
    yum:
      name: httpd-tools
      state: latest
    become: true

  - name: Configure nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0640
    become: true

  - name: Configure htpasswd.users
    copy:
      src: htpasswd.users
      dest: /etc/nginx/htpasswd.users
      owner: root
      group: root
      mode: 0644
    become: true

  - name: Start nginx
    service: name=nginx state=restarted enabled=yes
    become: true
